### PR TITLE
respect convert_to_snake_case settings

### PR DESCRIPTION
**Pull request by Rosswell**
fixes https://github.com/mirumee/ariadne-codegen/issues/275 by passing the `convert_to_snake_case` to various generators created via the `get_package_generator` function. 

adds a test that attempts to test that all the generator class fields that are determined by data passed in from `ClientSettings` are respected.

tested both via unit tests and by regenerating code in which i experienced this issue myself

### CODE REVIEW

**Comment by Rosswell** [comment]
@rafalp would you be able to take a look at this whenever you get a chance? very minor change

**Comment by rafalp** [comment]
Hi @Rosswell, @DamianCzajkowski is the man you want. I am no longer with Mirumee and I have no powers here anymore :D

**Comment by DamianCzajkowski** [comment]
Hi @Rosswell, could you add a changelog entry?

**Comment by Rosswell** [comment]
@DamianCzajkowski done!

**Comment by DamianCzajkowski** [comment]
I've checked it, and it looks fine. Just some linters failed, so after you resolve them, I will merge it and deploy a new version.

**Comment by Rosswell** [comment]
@DamianCzajkowski fixed :)

**Comment by McleanWorkshield** [comment]
Appreciate this feature - it solved my problem!

I look forward to it being deployed. In the mean time I successfully got it from git. 

I think the default feature is still broken though - Generated code works fine with the snake case. It breaks when trying to get nested properties. 

Either way thanks!!

**Pull request merged**
